apiVersion: v1
kind: ReplicationController
metadata:
  name: demo25
  namespace: com-att-ocnp-mgmt
spec:
  replicas: 1
  selector:
    app: demo25
  template:
    metadata:
      labels:
        app: demo25
    spec:
      serviceAccount: YOUR
      containers:
      - name: demo25
        image: ${docker-registry}/${docker-namespace}/demo25:latest
        imagePullPolicy: Always
        ports:
         - containerPort: 8080